### ISSUE TITLE
Plan

### ISSUE THREAD

**Issue by Ezharjan** [harshmuriki/CARLA-Semantic-Segmentation-YOLOv8#1]
Are you going to make a tool to automatically collect YOLO-style dataset in CARLA?
When do you plan to finish it?

**Comment by harshmuriki** [comment]
My plan was to collect datasets from CARLA and test numerous semantic segmentation models like YOLO, etc and gauge how accurate they are.

**Comment by Ezharjan** [comment]
> My plan was to collect datasets from CARLA and test numerous semantic segmentation models like YOLO, etc and gauge how accurate they are. I want to finish it by around June 15th. Do you have any suggestions on what I could add, etc?

Nice job!

In order to test different models, you have to ensure the input styles, which means that you may have to collect data and make them in different styles. 
There are many public repositories online that collect a specific type of dataset that you can refer to, such as in the form of KITTI, nuScenes, etc. But so far I haven't found one that collects YOLO-style dataset from CARLA. 
Looking forward to your achievement!
